blank_issues_enabled: false
contact_links:
  - name: Report issues related to Windows Terminal
    url: https://github.com/microsoft/terminal/issues
    about: Windows Terminal product repo (for reporting issues, bugs, or feature requests)
  - name: Report issues related to the Console
    url: https://github.com/MicrosoftDocs/Console-Docs/issues
    about: Windows Console repo (For reporting issues with CMD)